on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Use custom action
        id: custom-action
        uses: ./
        with:
          who-to-greet: 'Mona the Octocat'
      
      - name: Show random number
        run: echo "Random number: ${{ steps.custom-action.outputs.random-number }}"
        shell: bash
